poolApiUrl: http://38.46.219.171:3100
password: '123456'
accounts:
  parent:
    accountId: 1
    email: admin@artpayaws.site
    name: admin
    status: 0
    latestEmailTime: null
    createTime: '2025-12-04 11:14:14'
    userId: 1
    isDel: 0
  children:
    - accountId: 102
      email: I6WHpMHIqnCtpPv@artpayaws.site
      name: I6WHpMHIqnCtpPv
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:41:23'
      userId: 1
      isDel: 0
    - accountId: 103
      email: LewIwMQpZj4PHzt@artpayaws.site
      name: LewIwMQpZj4PHzt
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:41:23'
      userId: 1
      isDel: 0
      tokens:
        csesidx: '247102542'
        host_c_oses: COS.AfQtEyBfcFDL5-pGKvU0nf6FxYmD0NAc_JIosNA9rA-e51DVQ3-sKcJFSdvf7q-5Ss69W7K5t3P3rD0Eb9DjHxRZgT8eUbi5Dq5fpLVgqHujt_8cQQ6f_NkFV3Audy62ZDFMJxVdoSzFGfqZ
        secure_c_ses: CSE.AdwtfTB4cF2V7co2jh_sGzyRmf6kK96JjuREkIcu64RbEDjgo50ncEMEipsMzRpGfMIkViWQoCZC7yxjIX0PIGcX8CJCTBpeDoW7v3K6BP7Yirw7kJjAy02rCcJfR_EOUuW4-xTDrKeYeFXIOvLXN5MbHOeApayeQpq3eZeUU6PaG0glRAiLBY842MmebtiDHlOYc98nDPSimGXi_XTkd0ypoxzyD7x8-AX385HsETL9LSUPRTbgsB8GvlULi7agnDHEDedQldbTrycZSiOM9wdDtdEkRIfFNOGmOBpSKjqpAIEniQscyMRFLuSKH73eIlPfEwQJdvYjt7JB5j9-6XyIddfy0FEL1BgQSMuhUzXCYXsHhD_7tkwulx4eHBs5J9cmz8EzQnnuWvpsP3No9LRiZQzeLyYnIbAVDs5BCB-a0XaYdJeWPSGNhMuKi7Ukq796cAUxSU1f
        team_id: 89a5bfd6-7a6e-4786-9308-97ec7ffafa91
      lastUpdated: '2025-12-16T06:13:26.055Z'
    - accountId: 104
      email: g3i6GpSXZvgway2@artpayaws.site
      name: g3i6GpSXZvgway2
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:44:22'
      userId: 1
      isDel: 0
    - accountId: 105
      email: NDomK5qc3xf80xj@artpayaws.site
      name: NDomK5qc3xf80xj
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:44:22'
      userId: 1
      isDel: 0
      tokens:
        csesidx: '1141517261'
        host_c_oses: COS.AfQtEyBCt4v7h7Khsm6Mb4S8MbkGpLJ8k5ZrfJwGyr5CaQKT4CnxLdJwyZjmjfUH6yC8lZ57GXyocKSkTag9CwUBLGcNB_XvH7gAXS61Wj6IoAQbc77jrKNtguLIldSmYtQmLyw0s05FM97p
        secure_c_ses: CSE.AdwtfTAH6Jq10Br5vmUyqvK-JyOOJahHPMfevfSxBdnxpnQCJ4iQ66DPIiawLQ1yILBi8se23mTL40ItBJXhgSIwKU62Sf7b7iOFaaJJ53q8MhRQmjzP59XXq4KlIHhIdkBy_A0H4OGGkUJHVF8zKXUS-mwfXnDLLlsOL_BjsBUhcQhBfWWJkrI_NiwY3r9U-J8ADDxfoYtItGCf2DVz62cmGTOiQ15SHQpCYZV59aSZ_FJB-wbNXaI2e7sq9vCyNr9sK65p12HyazzfXdEIdo8hgeP6YXwsSb8JsFOKBggoEfWoukQ_YOfiphWJfGEgC7f0XiPVFq0vNEQTDBEw3fEBCdPIqFSJQcpkJd8Rc_czO9kBw4Nen9gq3PxOIgtKFZdf0lXfX6JJQ8L3JDxl3h5azr6cRtWX_GW0-t_TSOqkwrliULelnLFEiZqj11lB8oNY_XS5sklaXg
        team_id: aa244f18-82dd-4f39-8161-a888983677b3
      lastUpdated: '2025-12-16T06:14:48.936Z'
    - accountId: 106
      email: aC9MTe4GGusXnil@artpayaws.site
      name: aC9MTe4GGusXnil
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:44:30'
      userId: 1
      isDel: 0
      tokens:
        csesidx: '701678840'
        host_c_oses: COS.AfQtEyDQErgDDB5Gk2tFiSmFsNVwusLc8JG6fDOqUCL2-ziXC82qdKrkGu83WPCETHQOFv3_ZaBv1bH681IJmDh2B8DaVDUaaox25q_DnjFUqP3aGZlOFa8ISmTMfXrUPCMnS9wJKSbx6GmP
        secure_c_ses: CSE.AdwtfTDewrvk1LVLF4UGk2gV7YUyg6xwhkpEPvcXGvb0HnFcHi4k8qK9mH6mzUaoFC05b7YVk8UKuI_uPV-jNwgDGao6hkKHgJKcEs7P39sRCcXoHGSOGoVSA1HEKhuV9mTsHtbRk3cPxwhXu6PPp3z5TimgVkep5NMke22lP4tNU6VXBv9MqP3BwpaQWC0siX9R9jScbNSNtc0BuvHVYr3qgorT5rXLGpWFAc8U1MNcBZMTaBFf9UzSi2QPxLCP_rAyg-p4ExLH5yxsgb2fbweaildD2ulR1NHVHcwYl8I-2-tUMaYWbQror12hbwHfzjdsd5T9hVQytQbzrhuSETjteZMO2n8G0g1zCX4MHAPmIdUAv8mkWBQpGuH3wPrtthEU7fyc6g5yxfKE_2SQyNQOGitDMrD81u6SLdf-o-5SIrnbn4OJY-bDnxtARAfRqukIHFWg3zYrbA
        team_id: 136b55ba-972a-4434-a10a-c9ee7db813ae
      lastUpdated: '2025-12-16T06:15:28.200Z'
    - accountId: 107
      email: 25fxxGRTOGJRX3l@artpayaws.site
      name: 25fxxGRTOGJRX3l
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:44:30'
      userId: 1
      isDel: 0
    - accountId: 108
      email: DJyo3PnzoPYEd2i@artpayaws.site
      name: DJyo3PnzoPYEd2i
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 05:09:31'
      userId: 1
      isDel: 0
    - accountId: 109
      email: mQzLrXsa1jqbEU9@artpayaws.site
      name: mQzLrXsa1jqbEU9
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 05:09:31'
      userId: 1
      isDel: 0
    - accountId: 110
      email: VlmeLLckCEhLT7i@artpayaws.site
      name: VlmeLLckCEhLT7i
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 05:09:36'
      userId: 1
      isDel: 0
      tokens:
        csesidx: '2116523163'
        host_c_oses: COS.AfQtEyCvo1PBk6VPn9yqLTo0VLw2cgdfrLMY6hd6pJ5qOta3bxSFny3EvOvhH3NB4GAyLKHpvmubPViCO5MO0f3dajy_lVfJVsoRRTBNwY9-HXuMgFwehRxwBvCyB_nBWPLGJONHulpXcvk1
        secure_c_ses: CSE.AdwtfTBs2JRzjp2nIHFCthSEVLF88ZK3AJoEXyL-q9Y-0pJRTIJomaQVaxoGxgrPKm2JMtzHn8j0BqPhkpIzCtrkStlKJxWyLmwvMNCKhUMEOJziOKT4j1Bn2zCNfzxM-adVsVZ0rRcpfIe0vfg3rzhuu44jfo07l98ZoaV8yV1EhIZ47VcQNPJcZl-iFQGI2BzOYr_rqu4NWISC-b1tR-1B7274CO-YAB9Amg-E814uZIux1Qc0J3QiJytv0CIyYyF8lqbiSih2RV27CyvNgtRdv2sv-I9FwS5RQqWxq_YGRoDHV5ngunBTHDMP9IEnpj73idd6IYVLnqMqhU627PD4L3WlKwZUNgg2KFCAMddcQmdp7NApDc5xZwrUqVb5aDD5N5fLdoJycplot4NbQ9kwQZ_zQ_Fq1IIIDP8C1LCY3UtIyLXrfBdITRoWLJHbLcKUfXyYnPkgAg
        team_id: 992ecf5b-a1f2-4d67-8a94-4d570eb223fb
      lastUpdated: '2025-12-16T06:21:43.999Z'
    - accountId: 111
      email: lOuky9InRWE5EZm@artpayaws.site
      name: lOuky9InRWE5EZm
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 05:09:36'
      userId: 1
      isDel: 0
      tokens:
        csesidx: '889890746'
        host_c_oses: COS.AfQtEyBlkBBe9Py2JYDlJGB6cnJGR9cTCr7zt16C2Mx4jnCN5IZAGRlthBtD5ZAt9XUDeOIJ-mKDnd2POUTI0xmKFZrFK0Ho1aFLWyr7gncH1P1wBcTod86IdssPirwty2Pc_xB9f3pWAiML
        secure_c_ses: CSE.AdwtfTAFWv4nu_Huv3EpIA8c27KF8UiwBEctwSsX7JpNIPfusoKn26El5Xewcr1GkS2erzUUegMsAF9amIdrVy20QQhhRdBIQwhYbYZ-r8T3Xy1GA7wiTr-Jcv8xLu-xvahYT7CKLOfrSmmUy7X5py4u1__Sp9qoETMVaYrRbaXcUvOOY8ex6kkqdkLs-O4-QMWcgUgNwO3a4CXL1h3D-gEKGIGSwT09UXDIHMF_9qhMyjG7Mj64xBzs78tPdku4c-3t9qn60EfsEDodt7Im1uDN1C8Y45NEG1w7ZS-ZGYl-cdpu0sqN2y-jlGpowwKeCx_4r3WslzJ4rx5mppZxR7cfqjjAWINlcSsFR9ovRjcDAyoxYK05Db0ReRxywiJGWNk7aQ9FcASngndy2rllaMIWVaraCp9xLCOfq5rRpzevq2Z1TfWe7Yz88vpcuB-dtwdyMqvjb2DGpQ
        team_id: fc99df71-03ab-4795-a8d6-2d39fe0d7192
      lastUpdated: '2025-12-16T06:23:29.367Z'
