poolApiUrl: http://127.0.0.1ï¼š8000
password: '1'
accounts:
  parent:
    accountId: 1
    email: admin@artpayaws.site
    name: admin
    status: 0
    latestEmailTime: null
    createTime: '2025-12-04 11:14:14'
    userId: 1
    isDel: 0
  children:
    - accountId: 590
      email: 42kQHQJzILzi03r@artpayaws.site
      name: 42kQHQJzILzi03r
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:35:59'
      userId: 1
      isDel: 0
    - accountId: 591
      email: zURPjrJbT558Gt9@artpayaws.site
      name: zURPjrJbT558Gt9
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:35:59'
      userId: 1
      isDel: 0
    - accountId: 592
      email: MN8snOViSekKUPQ@artpayaws.site
      name: MN8snOViSekKUPQ
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:35:59'
      userId: 1
      isDel: 0
    - accountId: 593
      email: 6ZIUU1QFKOBnzDl@artpayaws.site
      name: 6ZIUU1QFKOBnzDl
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:35:59'
      userId: 1
      isDel: 0
    - accountId: 594
      email: MhCTkL0lHXPOqAs@artpayaws.site
      name: MhCTkL0lHXPOqAs
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 595
      email: eJExFDbgQnOIhgP@artpayaws.site
      name: eJExFDbgQnOIhgP
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 596
      email: UZn5F702OOdhJa6@artpayaws.site
      name: UZn5F702OOdhJa6
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 597
      email: UuW2ZLOZr7Y0k6r@artpayaws.site
      name: UuW2ZLOZr7Y0k6r
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 598
      email: r7vYtY7z9NZgrx0@artpayaws.site
      name: r7vYtY7z9NZgrx0
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 599
      email: 3VV8fO6stBzmFIA@artpayaws.site
      name: 3VV8fO6stBzmFIA
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 600
      email: g2XY87WxGEZdK3W@artpayaws.site
      name: g2XY87WxGEZdK3W
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 601
      email: ZZ7LqxV5GgM3adv@artpayaws.site
      name: ZZ7LqxV5GgM3adv
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 602
      email: Tw1FabKF9dWtgrJ@artpayaws.site
      name: Tw1FabKF9dWtgrJ
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 603
      email: kwQYHVAGSZQTzT0@artpayaws.site
      name: kwQYHVAGSZQTzT0
      status: 0
      latestEmailTime: null
      createTime: '2025-12-18 11:36:00'
      userId: 1
      isDel: 0
    - accountId: 604
      email: oOmQp3GHjrhozX7@artpayaws.site
      name: oOmQp3GHjrhozX7
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:22'
      userId: 1
      isDel: 0
    - accountId: 605
      email: GKwr8tf1pE1lSDW@artpayaws.site
      name: GKwr8tf1pE1lSDW
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:22'
      userId: 1
      isDel: 0
    - accountId: 606
      email: BD6Ay4KwVXcykK7@artpayaws.site
      name: BD6Ay4KwVXcykK7
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:22'
      userId: 1
      isDel: 0
    - accountId: 607
      email: 6fOCYfFUavCjF82@artpayaws.site
      name: 6fOCYfFUavCjF82
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:22'
      userId: 1
      isDel: 0
    - accountId: 608
      email: DMCQvfsYRHNRBl6@artpayaws.site
      name: DMCQvfsYRHNRBl6
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:22'
      userId: 1
      isDel: 0
    - accountId: 609
      email: n0xaHr8y84ZJpdc@artpayaws.site
      name: n0xaHr8y84ZJpdc
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:23'
      userId: 1
      isDel: 0
    - accountId: 610
      email: utTrr4J5r9OcmLL@artpayaws.site
      name: utTrr4J5r9OcmLL
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:23'
      userId: 1
      isDel: 0
    - accountId: 611
      email: OJTWMN45RVfvX35@artpayaws.site
      name: OJTWMN45RVfvX35
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:23'
      userId: 1
      isDel: 0
    - accountId: 612
      email: wNgUQTcRzsAOcFp@artpayaws.site
      name: wNgUQTcRzsAOcFp
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:23'
      userId: 1
      isDel: 0
    - accountId: 613
      email: fcQT5g1tJVhX8JT@artpayaws.site
      name: fcQT5g1tJVhX8JT
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:23'
      userId: 1
      isDel: 0
    - accountId: 614
      email: qSNeclgMeBjSGcU@artpayaws.site
      name: qSNeclgMeBjSGcU
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:23'
      userId: 1
      isDel: 0
    - accountId: 615
      email: IdXpAb6LCeRa5EW@artpayaws.site
      name: IdXpAb6LCeRa5EW
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:24'
      userId: 1
      isDel: 0
    - accountId: 616
      email: YfuljiDy2TklrVJ@artpayaws.site
      name: YfuljiDy2TklrVJ
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:24'
      userId: 1
      isDel: 0
    - accountId: 617
      email: jL7FRcJE92JeMK0@artpayaws.site
      name: jL7FRcJE92JeMK0
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:24'
      userId: 1
      isDel: 0
    - accountId: 618
      email: alUtIWdgxNEVdwK@artpayaws.site
      name: alUtIWdgxNEVdwK
      status: 0
      latestEmailTime: null
      createTime: '2025-12-20 03:20:24'
      userId: 1
      isDel: 0
