poolApiUrl: http://127.0.0.1:8000
password: '1'
accounts:
  parent:
    accountId: 1
    email: admin@artpayaws.site
    name: admin
    status: 0
    latestEmailTime: null
    createTime: '2025-12-04 11:14:14'
    userId: 1
    isDel: 0
  children:
    - accountId: 87
      email: LYsxjrGipMBcToW@artpayaws.site
      name: LYsxjrGipMBcToW
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:54:56'
      userId: 1
      isDel: 0
    - accountId: 88
      email: PVns07JcLtUVprN@artpayaws.site
      name: PVns07JcLtUVprN
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:54:56'
      userId: 1
      isDel: 0
    - accountId: 89
      email: PGpNX08Vm8PbtVj@artpayaws.site
      name: PGpNX08Vm8PbtVj
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:54:56'
      userId: 1
      isDel: 0
    - accountId: 90
      email: hO8VI7710CHVpUx@artpayaws.site
      name: hO8VI7710CHVpUx
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:54:56'
      userId: 1
      isDel: 0
    - accountId: 91
      email: 57gzBLIjEzkH8zd@artpayaws.site
      name: 57gzBLIjEzkH8zd
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:54:56'
      userId: 1
      isDel: 0
