poolApiUrl: http://127.0.0.1:8000
password: '1'
accounts:
  parent:
    accountId: 1
    email: admin@artpayaws.site
    name: admin
    status: 0
    latestEmailTime: null
    createTime: '2025-12-04 11:14:14'
    userId: 1
    isDel: 0
  children:
    - accountId: 24
      email: n7lMzxwzS0LwWvz@artpayaws.site
      name: n7lMzxwzS0LwWvz
      status: 0
      latestEmailTime: null
      createTime: '2025-12-14 01:14:44'
      userId: 1
      isDel: 0
