poolApiUrl: http://127.0.0.1:8000
password: '1'
accounts:
  parent:
    accountId: 1
    email: admin@artpayaws.site
    name: admin
    status: 0
    latestEmailTime: null
    createTime: '2025-12-04 11:14:14'
    userId: 1
    isDel: 0
  children:
    - accountId: 54
      email: H2znWcdZIGEmOd6@artpayaws.site
      name: H2znWcdZIGEmOd6
      status: 0
      latestEmailTime: null
      createTime: '2025-12-14 03:45:07'
      userId: 1
      isDel: 0
    - accountId: 55
      email: qAQZ7JN3O5mmsyz@artpayaws.site
      name: qAQZ7JN3O5mmsyz
      status: 0
      latestEmailTime: null
      createTime: '2025-12-14 03:45:07'
      userId: 1
      isDel: 0
    - accountId: 56
      email: QcDhXKbXMKT49lt@artpayaws.site
      name: QcDhXKbXMKT49lt
      status: 0
      latestEmailTime: null
      createTime: '2025-12-14 03:45:07'
      userId: 1
      isDel: 0
    - accountId: 57
      email: 7C8vQmfrPCrY9JS@artpayaws.site
      name: 7C8vQmfrPCrY9JS
      status: 0
      latestEmailTime: null
      createTime: '2025-12-14 04:41:18'
      userId: 1
      isDel: 0
    - accountId: 58
      email: tzWBaZFChX62EYc@artpayaws.site
      name: tzWBaZFChX62EYc
      status: 0
      latestEmailTime: null
      createTime: '2025-12-14 04:41:18'
      userId: 1
      isDel: 0
