credentials:
  account: admin
  password: '123456'
defaultDomain: '@artpayaws.site'
emailApiUrl: https://artpayaws.site
accounts:
  parent:
    accountId: 1
    email: admin@artpayaws.site
    name: admin
    status: 0
    latestEmailTime: null
    createTime: '2025-12-04 11:14:14'
    userId: 1
    isDel: 0
  children:
    - accountId: 75
      email: GG5gzSaxdv0MIHC@artpayaws.site
      name: GG5gzSaxdv0MIHC
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:00:01'
      userId: 1
      isDel: 0
    - accountId: 76
      email: KV4tcOQU2sxeEib@artpayaws.site
      name: KV4tcOQU2sxeEib
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:00:01'
      userId: 1
      isDel: 0
    - accountId: 77
      email: zkryE8La1iBDnkv@artpayaws.site
      name: zkryE8La1iBDnkv
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:16:07'
      userId: 1
      isDel: 0
    - accountId: 78
      email: 0Cra0oXlqv2xfF0@artpayaws.site
      name: 0Cra0oXlqv2xfF0
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:16:07'
      userId: 1
      isDel: 0
    - accountId: 79
      email: ukJ4a6tSlEu1yts@artpayaws.site
      name: ukJ4a6tSlEu1yts
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:16:07'
      userId: 1
      isDel: 0
    - accountId: 80
      email: EI1YLjEEPljcxYI@artpayaws.site
      name: EI1YLjEEPljcxYI
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:16:07'
      userId: 1
      isDel: 0
    - accountId: 81
      email: gTVsKZWTP8SCiGb@artpayaws.site
      name: gTVsKZWTP8SCiGb
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:16:07'
      userId: 1
      isDel: 0
    - accountId: 82
      email: YN57Pg3U5w1YgVR@artpayaws.site
      name: YN57Pg3U5w1YgVR
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:44:50'
      userId: 1
      isDel: 0
    - accountId: 83
      email: n3POb8GyNu3Ewaa@artpayaws.site
      name: n3POb8GyNu3Ewaa
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:44:50'
      userId: 1
      isDel: 0
    - accountId: 84
      email: CrFqo21xSLeERce@artpayaws.site
      name: CrFqo21xSLeERce
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:44:50'
      userId: 1
      isDel: 0
    - accountId: 85
      email: JrMUStcjkLavmFM@artpayaws.site
      name: JrMUStcjkLavmFM
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:44:50'
      userId: 1
      isDel: 0
    - accountId: 86
      email: cyIJFaRqxzu8sJ9@artpayaws.site
      name: cyIJFaRqxzu8sJ9
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 01:44:50'
      userId: 1
      isDel: 0
  lastUpdated: '2025-12-16T01:48:57.330Z'
