credentials:
  account: admin
  password: '123456'
defaultDomain: '@artpayaws.site'
emailApiUrl: https://artpayaws.site
accounts:
  parent:
    accountId: 1
    email: admin@artpayaws.site
    name: admin
    status: 0
    latestEmailTime: null
    createTime: '2025-12-04 11:14:14'
    userId: 1
    isDel: 0
  children:
    - accountId: 102
      email: I6WHpMHIqnCtpPv@artpayaws.site
      name: I6WHpMHIqnCtpPv
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:41:23'
      userId: 1
      isDel: 0
    - accountId: 103
      email: LewIwMQpZj4PHzt@artpayaws.site
      name: LewIwMQpZj4PHzt
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:41:23'
      userId: 1
      isDel: 0
    - accountId: 104
      email: g3i6GpSXZvgway2@artpayaws.site
      name: g3i6GpSXZvgway2
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:44:22'
      userId: 1
      isDel: 0
    - accountId: 105
      email: NDomK5qc3xf80xj@artpayaws.site
      name: NDomK5qc3xf80xj
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:44:22'
      userId: 1
      isDel: 0
    - accountId: 106
      email: aC9MTe4GGusXnil@artpayaws.site
      name: aC9MTe4GGusXnil
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:44:30'
      userId: 1
      isDel: 0
    - accountId: 107
      email: 25fxxGRTOGJRX3l@artpayaws.site
      name: 25fxxGRTOGJRX3l
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 04:44:30'
      userId: 1
      isDel: 0
    - accountId: 108
      email: DJyo3PnzoPYEd2i@artpayaws.site
      name: DJyo3PnzoPYEd2i
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 05:09:31'
      userId: 1
      isDel: 0
    - accountId: 109
      email: mQzLrXsa1jqbEU9@artpayaws.site
      name: mQzLrXsa1jqbEU9
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 05:09:31'
      userId: 1
      isDel: 0
    - accountId: 110
      email: VlmeLLckCEhLT7i@artpayaws.site
      name: VlmeLLckCEhLT7i
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 05:09:36'
      userId: 1
      isDel: 0
    - accountId: 111
      email: lOuky9InRWE5EZm@artpayaws.site
      name: lOuky9InRWE5EZm
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 05:09:36'
      userId: 1
      isDel: 0
  lastUpdated: '2025-12-16T06:12:04.781Z'
