credentials:
  account: admin
  password: '123456'
defaultDomain: '@artpayaws.site'
emailApiUrl: https://artpayaws.site
accounts:
  parent:
    accountId: 1
    email: admin@artpayaws.site
    name: admin
    status: 0
    latestEmailTime: null
    createTime: '2025-12-04 11:14:14'
    userId: 1
    isDel: 0
  children:
    - accountId: 69
      email: LcHGYRNQAhfXX1K@artpayaws.site
      name: LcHGYRNQAhfXX1K
      status: 0
      latestEmailTime: null
      createTime: '2025-12-15 23:03:54'
      userId: 1
      isDel: 0
    - accountId: 70
      email: mbLolNwFTGrS4GR@artpayaws.site
      name: mbLolNwFTGrS4GR
      status: 0
      latestEmailTime: null
      createTime: '2025-12-15 23:03:54'
      userId: 1
      isDel: 0
  lastUpdated: '2025-12-15T23:04:38.143Z'
