credentials:
  account: admin
  password: '123456'
defaultDomain: '@artpayaws.site'
emailApiUrl: https://artpayaws.site
accounts:
  parent:
    accountId: 1
    email: admin@artpayaws.site
    name: admin
    status: 0
    latestEmailTime: null
    createTime: '2025-12-04 11:14:14'
    userId: 1
    isDel: 0
  children:
    - accountId: 71
      email: 1piSEVKiACHI223@artpayaws.site
      name: 1piSEVKiACHI223
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 00:18:06'
      userId: 1
      isDel: 0
    - accountId: 72
      email: JE7EpFL8jkXZhl7@artpayaws.site
      name: JE7EpFL8jkXZhl7
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 00:18:06'
      userId: 1
      isDel: 0
    - accountId: 73
      email: lODHNciOWSlpern@artpayaws.site
      name: lODHNciOWSlpern
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 00:26:13'
      userId: 1
      isDel: 0
    - accountId: 74
      email: nmrXGjq5tQiyE90@artpayaws.site
      name: nmrXGjq5tQiyE90
      status: 0
      latestEmailTime: null
      createTime: '2025-12-16 00:26:13'
      userId: 1
      isDel: 0
  lastUpdated: '2025-12-16T00:53:34.209Z'
